### ISSUE TITLE
[Suggestion] Adding Inventory Restore Command

### ISSUE THREAD

**Issue by Gbergz** [Nuclearfarts/yet-another-gravestone-mod#1]
Hey! Can i make a suggestion on a command that could be added?
A restore inventory command "/invrestore <name> (date)" etc.

 
Would be really handy. Just lost my grave for some weird reason. Sad that i couldn't restore my inv.

**Comment by TwilightFlower** [comment]
That is out of scope for this project. Would require storing the inventory somewhere else that's associated with the player and not just a position in the world, and that's not really that easy. I'm sure there are other mods that can do this, however.
